version: "3"
services:
  kungfu:
    build: .
    hostname: kungfu
    restart: always
    privileged: true
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data/kungfu/config:/config

  prometheus:
    image: prom/prometheus:v2.39.1
    hostname: prometheus
    restart: always
    user: root
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    volumes:
      - ./data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus/config:/config
      - prometheus_data:/prometheus
    depends_on:
      - kungfu

  # default user/password: admin/admin
  grafana:
    image: grafana/grafana:9.1.7
    hostname: grafana
    restart: always
    user: root
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  prometheus_data:
  grafana_data: